language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
- nightly
- beta
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  cargo build --no-default-features &&
  cargo clean &&
  cargo build &&
  cargo test &&
  travis-cargo --only nightly bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: jb9DJNnUf+5DrDFtg8w3cUtBldvpjvhr6lap5TYeuwc9yK3mdn3vxPL860MfghwmBrcPt3oRQH/QPDUbqN+Xhm/+u2859cWvNbnnH2m9J9BuVlWTNweBeCvrCD35Qto1PADCYC6yOvtEm7Z4h3Qy/bRCjNg4osUx04G7ouO1chocc8WM/NqDJD7/9s1kxkLMlowDom3ftpmlgV0y47uNRjIaw0PD53Udn9kIoJ7qddA/4yUcZZVWm+xsM/UZZOHN+dtTzxNdbCg52LmrnPpbE5nAdUx+c6tOwb+JolIVIUl4TP6Rc19cxz50rGJJJRuSbVNZm2nqRS6MUuAx7YRms6+aCXFkOHbAO2sl6B7eU9u+UmttWo1A4CjIexCMZU4OsVX54aTj67Lm9QHBrd665UGx7G7Mc4VyghKTA+0RKLw5xiYufcSgmBOc7c4jg97k3L6XJ70Pmh5QV+i+e28SoLbspHe3qN0k2TgvK1AcqFDaZWg/gS9hvmjg2eoHFeQYnKPbhH5XZz7JHiKawBqxb6GI6nO9+WGRkcKn3KWv6UTdH/PL1RZWDm1ItnTh+XVcDKuaak9nSQnicDG2RQ/bQ08gNyxqf0tOkfZJxkbKadb3PDcKcZHaTl9J/0MWmDaa5qCTqthkqTJt37XlZhxsylpJVeCi/vrvxa3pDD1uWBc=
